"use client"

// import type { Metadata } from 'next'
import './globals.css'
import { inter, roboto } from './font'
import AdminLayout from './adminLayout'
import { MenuProvder } from './menus/context'
import { OrderProvder } from './order/context'


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className='flex gap-4'>
        <MenuProvder>
          <OrderProvder>
            <AdminLayout />
            {children}
          </OrderProvder>
        </MenuProvder>

      </body>

    </html>
  )
}
